version: "3.8"
services:
  frontend:
    volumes:
      - type: bind
        source: ../
        target: /app
    build:
      dockerfile: ../docker/Dockerfile.frontend
    command: bash -c "cd app/frontend && trunk serve --address 0.0.0.0"
    environment:
      - ACTIX_PORT=8086
      - TRUNK_SERVE_PORT=8080
    ports:
      - "8080:8080"
  server:
    build:
      dockerfile: ../docker/Dockerfile.server
    command: bash -c "cd app/server && cargo watch -x \"run\""
    environment:
      - ACTIX_PORT=8086
      - TRUNK_SERVE_PORT=8080
      - TRUNK_SERVE_HOST=localhost
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ../
        target: /app
